"""empty message

Revision ID: 3e17c15187c5
Revises:
Create Date: 2023-02-16 00:54:53.855111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3e17c15187c5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cat")
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('user_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.VARCHAR(length=15), autoincrement=False, nullable=False
        ),
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "nickname", sa.VARCHAR(length=15), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
        sa.UniqueConstraint("nickname", name="user_nickname_key"),
        sa.UniqueConstraint("user_id", name="user_user_id_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "cat",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("represent_cat", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=15), autoincrement=False, nullable=False),
        sa.Column("birth", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("img", sa.VARCHAR(length=2083), autoincrement=False, nullable=True),
        sa.Column("gender", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column(
            "species", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("weight", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="cat_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="cat_pkey"),
    )
    # ### end Alembic commands ###
