name: learn-github-actions
on:
  push:
    branches:
      - feature/*
jobs:
  run-pytests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install -r requirements.dev.txt
      - run: pytest 
